version: '3.9'
services:
  server:
    image: nginx
    ports:
      - 80:80
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
  front:
    build: ./front
  back:
    build: ./back
    volumes:
      - $PWD/db:/usr/src/app/db